kind: pipeline
name: build-and-test-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build-and-test
  image: gcc
  commands:
  - mkdir -p bin && cd bin
  - curl -L https://github.com/bazelbuild/bazel/releases/download/4.0.0/bazel-4.0.0-linux-arm64 -o bazel && chmod +x bazel
  - cd ..
  - ./bin/bazel -c fastbuild --cxxopt -std=c++17 build //...:all
  - ./bin/bazel -c fastbuild --cxxopt -std=c++17 test //...:all
  - ./bin/bazel -c dbg --cxxopt -std=c++17 build //...:all
  - ./bin/bazel -c dbg --cxxopt -std=c++17 test //...:all
  - ./bin/bazel -c opt --cxxopt -std=c++17 build //...:all
  - ./bin/bazel -c opt --cxxopt -std=c++17 test //...:all
